---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  # - ./pvc-config.yaml
  - ./helmrelease.yaml
  - ../../../../templates/volsync
  # - ./secret.sops.yaml
  # - ./volsync.yaml
